version: "3.9"

secrets:
  pipeline_api: { file: ./secrets/pipeline_api }
  llm_api:      { file: ./secrets/llm_api }   # Google Gemini 엔드포인트
  api_key:      { file: ./secrets/api_key }   # Google API-Key

services:
  reportgen:
    build:
      context: .
      dockerfile: docker/Dockerfile

    ports:
      - "8124:8000"          # FastAPI / Swagger

    # 입력·출력 디렉터리
    volumes:
      - ./data:/opt/app/data:ro    # STT 원문
      - ./out:/opt/app/out         # HTML / PDF 결과

    # Docker Secrets
    secrets:
      - pipeline_api
      - llm_api
      - api_key

    environment:
      PYTHONUNBUFFERED: "1"

    # DNS / host.docker.internal (Windows / macOS)
    dns:
      - 8.8.8.8
      - 1.1.1.1
    extra_hosts:
      - "host.docker.internal:host-gateway"
