secrets:                       # Compose-native secrets
  pipeline_api:
    file: ./secrets/pipeline_api
  llm_api:                     # ← 추가: LLM 엔드포인트
    file: ./secrets/llm_api
  api_key:
    file: ./secrets/api_key

services:
  reportgen:
    build:
      context: .
      dockerfile: docker/Dockerfile

    # 입력·출력 디렉터리 마운트
    volumes:
      - ./data:/opt/app/data:ro    # STT 입력
      - ./out:/opt/app/out         # PDF 출력

    # 시크릿 마운트
    secrets:
      - pipeline_api
      - llm_api        # ← 추가
      - api_key

    # DNS 서버 지정(외부 도메인 name-resolution 안정화)
    dns:
      - 8.8.8.8    # Google Public DNS
      - 1.1.1.1    # Cloudflare DNS

    # host.docker.internal 별칭(Windows/macOS 호스트 접근)
    extra_hosts:
      - "host.docker.internal:host-gateway"

    environment:
      PYTHONUNBUFFERED: "1"
