version: 1

# ──────────────── 콘솔 핸들러 ────────────────
handlers:
  console:
    class: rich.logging.RichHandler
    level: DEBUG                      # DEBUG 허용
    rich_tracebacks: true
    markup: true
    log_time_format: "%Y-%m-%d %H:%M:%S"

# ──────────────── 로거 설정 ─────────────────
loggers:
  # 제3-자 라이브러리 ― 너무 시끄러운 DEBUG 억제
  httpx:            { level: WARNING, propagate: false, handlers: [console] }
  httpcore:         { level: WARNING, propagate: false, handlers: [console] }
  fontTools.subset: { level: WARNING, propagate: false, handlers: [console] }
  weasyprint:       { level: INFO,    propagate: false, handlers: [console] }

  # 우리 앱 소스는 DEBUG 까지 출력
  src:              { level: DEBUG,   propagate: true,  handlers: [console] }

# ──────────────── 루트 로거 ─────────────────
root:
  level: INFO                          # 기본은 INFO
  handlers: [console]
