version: 1

# ─ 개별 라이브러리 로그 억제 ──────────────────────────────
loggers:
  httpx:               { level: WARNING, propagate: false }
  httpcore:            { level: WARNING, propagate: false }
  fontTools.subset:    { level: WARNING, propagate: false }
  weasyprint:          { level: INFO,    propagate: false }   # PDF 생성 과정 INFO까지만

# ─ 핸들러 ────────────────────────────────────────────────
handlers:
  console:
    class: rich.logging.RichHandler
    level: DEBUG                # DEBUG 허용
    rich_tracebacks: true
    markup: true
    log_time_format: "%Y-%m-%d %H:%M:%S"

# ─ root 로거 ────────────────────────────────────────────
root:
  level: INFO                   # root는 INFO로 낮춰 불필요한 DEBUG 차단
  handlers: [console]

# ─ 우리 코드 패키지별 DEBUG 허용 ───────────────────────
  # 필요하면 추가
loggers:
  src: { level: DEBUG }
